### ISSUE TITLE
omeka s 4.0

### ISSUE THREAD

**Issue by johnhtx** [indic-archive/bookshelf#1]
Theme does not work with 4.0

**Comment by knadh** [comment]
Yeah, haven't had a chance to work on this. @joeirimpan maybe you could take a look?

**Comment by joeirimpan** [comment]
ah yes. I will try omeka 4.0 once.

**Comment by joeirimpan** [comment]
@johnhtx [v2.0.1](https://github.com/indic-archive/bookshelf/releases/tag/v2.0.1) has got support for omeka v4.
